skillMetadata:
  sections:
    - name: Configuration
      fields:
        - type: label
          label: Default duration (in seconds) for skipping forward/backward
        - name: default_duration
          type: number
          label: Default duration
          value: 30